### ISSUE TITLE
Question about filtering pmtiles

### ISSUE THREAD

**Issue by SebKrantz** [bdon/overture-tiles#4]
Hi @bdon,

first of all thanks a lot for providing this example. It is cool to see that you actually have a confidence filter on the map which seems to filter the pmtiles file. 

I am thinking about an app to serve a similarly large curated places dataset, with filtering and download options. The app should be interactive containing a data table view and a linked map, and input fields to query both on at least 2 categorical fields (and ideally a custom input field for full SQL queries). 

My thinking as of now is that this is not possible with a single pmtiles file (matching a simple SQL database so the app can query both), and that I would have to put the data into a PostGIS database and configure a [martin](https://github.com/maplibre/martin) server to generate vector tiles on the fly. But seeing this example made me think maybe it is possible?

 It would be great to hear your take in this. And thanks for all your work!

**Comment by bdon** [comment]
If you want to execute SQL on the backend that affects what tile data is returned then PMTiles is not enough. Some PostGIS-based solution works best. I just made this example of returning dynamic vector tiles using ST_asMVT from Supabase : https://github.com/bdon/supabase-vector-tile

**Comment by SebKrantz** [comment]
Thanks a lot for the fast answer and the example! In my case the whole data would fit into a single PMtiles, and for my visualization purposes it would suffice to have filters on two different attributes, but I guess having a tabular view of the data adjust concurrently will make a server-side implementation necessary. I'll look further into it.
